# Generated by Django 4.1.5 on 2023-02-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='In Progress', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to='onboarding.user')),
            ],
        ),
    ]
