# Generated by Django 4.1.5 on 2023-02-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('Book', 'Book'), ('Article', 'Article')], default='Movie', max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('image_url', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('author_director', models.CharField(max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='onboarding.user')),
            ],
        ),
    ]
